// Class automatically generated by Dev-C++ New Class wizard
#include <iostream>
#include "cajeroconsola.h" // class's header file

using namespace std;

CajeroConsola::CajeroConsola()
{
	this->cajero = Cajero(5,5,10,20);
}

void CajeroConsola::pedirSaldo(){
     cout << endl << endl << "SU SALDO ES: " << this->cajero.saldo() << endl;     
}

void CajeroConsola::sacarDinero(){
     int importe;
     int billetes_retirados[NUM_BILLETES];
     
     do {
         cout << endl << endl;
         cout << "Introduzca importe a retirar:";
         cin >> importe;
         
         if (importe <= 0 || importe % 10 != 0)
            cout << endl << "El importe NO es correcto" << endl;
         
     } while (importe <= 0 || importe % 10 != 0);
     
     if (this->cajero.retirar(importe, billetes_retirados)){
       cout << endl << "Billetes retirados" << endl;
       int *tiposBilletes = this->cajero.getTiposBilletes();
       
       for (int i = 0 ; i < NUM_BILLETES ; i++)
           if (billetes_retirados[i] > 0)
              cout << "De " << tiposBilletes[i] << ": " << billetes_retirados[i] <<  endl;                                   
    }   
     
}

void CajeroConsola::ingresarDinero(){
     int b100,b50,b20,b10;
     int importe;
     
     cout << endl << "Introduzca los billetes a ingresar" << endl;
     cout << "De 100: ";
     cin >> b100;
     
     cout << "De 50: ";
     cin >> b50;
     
     cout << "De 20: ";
     cin >> b20;
     
     cout << "De 10: ";
     cin >> b10;
     
     importe = this->cajero.ingresar(b100,b50,b20,b10);
     cout << endl << "Ha ingresado " << importe << endl << endl;
     
}

void CajeroConsola::pintarMenu(){
     
     cout << endl << endl << "MENU PRINCIPAL" << endl << endl;
     cout << "Seleccione una opcion:" << endl;
     cout << "1. Consultar saldo" << endl;
     cout << "2. Ingresar dinero" << endl;
     cout << "3. Retirar dinero" << endl;
     cout << "4. SALIR" << endl << endl;
     cout << "Opcion: ";
}

void CajeroConsola::menu(){
     int op;
     
     do {
         this->pintarMenu();
         cin >> op;
         
         switch(op){
           case SALDO:
                this->pedirSaldo();
                break;
                
           case INGRESO:
                this->ingresarDinero();
                break;
                
           case REINTEGRO:  
                this->sacarDinero();
                break;                      
           }
         
     } while (op != SALIR);     
}

CajeroConsola::~CajeroConsola()
{
	
}
