// Class automatically generated by Dev-C++ New Class wizard

#ifndef CAJEROCONSOLA_H
#define CAJEROCONSOLA_H

#include "cajero.h"

#define SALDO 1
#define INGRESO 2
#define REINTEGRO 3
#define SALIR 4

class CajeroConsola
{
    private:
        Cajero cajero;
        void pedirSaldo();
        void sacarDinero();
        void ingresarDinero();
        void pintarMenu();
        
	public:
		CajeroConsola();
		void menu();
		~CajeroConsola();
};

#endif // CAJEROCONSOLA_H
