// Class automatically generated by Dev-C++ New Class wizard

#include "cliente.h" // class's header file


// class constructor
Cliente::Cliente(string nif, string nombre)
{
	this->nif = nif;
	this->nombre = nombre;
}

ostream & operator<<(ostream &os, const Cliente &c){
        return os << c.nif << " " << c.nombre;        
}

// class destructor
Cliente::~Cliente()
{
	// insert your code here
}
