// Class automatically generated by Dev-C++ New Class wizard

#include "cuentabancaria.h" // class's header file

// class constructor
CuentaBancaria::CuentaBancaria(string nc,int clave,int pass,double saldo,Cliente titular)
{
	this->numeroCuenta = nc;
	this->clave = clave;
	this->password = pass;
	this->saldo = saldo;
	this->titular = titular;
}

void CuentaBancaria::imprimir(){
        cout << "cc: " << this->numeroCuenta << endl << 
                     "clave: " << this->clave << endl << 
                     "pass: " << this->password << endl << 
                     "saldo: " << this->saldo <<  endl <<
                     "titular: " << this->titular << endl;        
}

// class destructor
CuentaBancaria::~CuentaBancaria()
{
	// insert your code here
}
