// Class automatically generated by Dev-C++ New Class wizard

#ifndef CUENTABANCARIA_H
#define CUENTABANCARIA_H

#include <string>
#include <iostream>
using namespace std;

#include "cliente.h"

class CuentaBancaria
{
    
    protected:
            string numeroCuenta;
            int clave;
            int password;
            double saldo;
            Cliente titular;
            
	public:
		CuentaBancaria(string,int,int,double,Cliente);
		virtual inline void actualizarSaldo(double importe){ this->saldo += importe; }
		inline double getSaldo(){ return this->saldo; }		
		virtual void imprimir();
		~CuentaBancaria();
};

#endif // CUENTABANCARIA_H
