// Class automatically generated by Dev-C++ New Class wizard

#include "cuentadeahorro.h" // class's header file

// class constructor
CuentaDeAhorro::CuentaDeAhorro(string nc,int clave,int pass,double saldo,Cliente c,double penalizacion):
     CuentaBancaria(nc,clave,pass,saldo,c)
{
	this->penalizacion = penalizacion;
}

void CuentaDeAhorro::actualizarSaldo(double importe)
{
     if (importe < 0) 
        importe = importe + (importe * this->penalizacion / 100.0);
        
     CuentaBancaria::actualizarSaldo(importe);   
}

void CuentaDeAhorro::imprimir(){
     CuentaBancaria::imprimir();
     cout << "penalizacion: " << this->penalizacion << endl;      
}

// class destructor
CuentaDeAhorro::~CuentaDeAhorro()
{
	// insert your code here
}
