// Class automatically generated by Dev-C++ New Class wizard

#ifndef BANCOFILE_H
#define BANCOFILE_H

#include <vector>
#include <string>
#include "CuentaBancaria.h"
#include "CuentaDeAhorro.h"

using namespace std;

class BancoFile
{
	public:
		BancoFile();
		vector<CuentaBancaria *> load(string);
		bool save(vector<CuentaBancaria *>, string);
		~BancoFile();
};

#endif // BANCOFILE_H
