// Class automatically generated by Dev-C++ New Class wizard

#ifndef BANCO_H
#define BANCO_H

#include <vector>
#include <iostream>
using namespace std;

#include "CajeroConsola.h"
#include "CuentaBancaria.h"

#include <string>
using namespace std;

#define LISTAR 1
#define CAJERO 2
#define SALDO_CAJERO 3
#define SALIR_BANCO 4

class Banco
{
    private:
        vector<CuentaBancaria *> cuentas;
        CajeroConsola cajeroConsola;
        string fichero;
        
        void pintarMenu();
        void listarCuentas();
		void operarConCajero();
		void consultarSaldoCajero();
		void grabarCuentas();
		
	public:
		Banco(string, string);
		void menu();
		~Banco();
};

#endif // BANCO_H
