// Class automatically generated by Dev-C++ New Class wizard

#include "bancofile.h" 
#include "bancoexception.h"
#include "util.h"

#include <fstream>
#include <string>
#include <vector>

using namespace std;

// class constructor
BancoFile::BancoFile()
{
	
}

vector<CuentaBancaria *> BancoFile::load(string fichero)
{
    // Leer el fichero y cargar en un vector:
    fstream f;
    string linea;
    vector<string> campos;
    char tipo;
    vector<CuentaBancaria *> cuentas;
    
    // Grabar texto   
    f.open(fichero.c_str(),ios::in);
    if (!f){
             throw BancoException("ERROR al abrir el fichero: " + fichero);
    }
    while (getline(f,linea)){
          campos.clear();
          split(linea, ';',campos);
          
          tipo = campos.at(0).at(0);
          if (tipo == 'B')
             cuentas.push_back(new CuentaBancaria(campos));
             
          else if (tipo == 'A')
               cuentas.push_back(new CuentaDeAhorro(campos));                           
    }
    f.close();      
    return cuentas;
}

bool BancoFile::save(vector<CuentaBancaria *> v, string fichero)
{
    // Grabar el vector en un fichero:
    fstream f;
    string linea, tipo;
    
    // Grabar texto   
    f.open(fichero.c_str(), ios::out);
    if (!f){
            throw BancoException("ERROR al grabar el fichero: " + fichero);
    }
    
    for (int i = 0 ; i < v.size() ; i++){
        linea = v.at(i)->toCSV();
        tipo = v.at(i)->getTipo();
        
        f << tipo << ";" << linea << "\n";
        
    }
    f.close(); 
    return true;
}


BancoFile::~BancoFile()
{

}
