// Class automatically generated by Dev-C++ New Class wizard

#ifndef BANCOEXCEPTION_H
#define BANCOEXCEPTION_H

#include <stdexcept>
#include <string>
using namespace std;

class BancoException: public exception
{
    private:
            string mensaje;
            
	public:
		BancoException(string mensaje):exception(){this->mensaje=mensaje;}
        virtual const char *what() throw() { return mensaje.c_str(); }
		virtual ~BancoException() throw() {}
};

#endif // BANCOEXCEPTION_H
