// Class automatically generated by Dev-C++ New Class wizard

#include "banco.h"
#include "bancofile.h" 
#include "cuentabancaria.h"
#include "cuentadeahorro.h"

Banco::Banco(string ficheroCuentas, string ficheroCajero)
{
    BancoFile bf;
    
    this->fichero = ficheroCuentas;
    this->cuentas = bf.load(ficheroCuentas);
    this->cajeroConsola = CajeroConsola(ficheroCajero);
}

void Banco::listarCuentas(){
     cout << endl << endl << "LISTADO DE CUENTAS" << endl;
     cout <<         "==================" << endl <<endl;
     for (int i = 0 ; i < this->cuentas.size() ; i++){
         this->cuentas.at(i)->imprimir();
         cout << endl << "-----------------------------------" << endl;
     }
}

void Banco::operarConCajero(){
     int clave, pass;
     CuentaBancaria *cuentaSeleccionada = 0;
     
     cout << endl << "Operaciones con el Cajero" << endl;
     cout << "Teclear usuario y password" << endl;
     cout << "Usuario / Clave: ";
     cin >> clave;
     cout << "Password: ";
     cin >> pass;
     
     for (int i = 0 ; i < this->cuentas.size() ; i++)
         if (this->cuentas.at(i)->validar(clave, pass)){
            cuentaSeleccionada = this->cuentas.at(i);
         }
         
      if (cuentaSeleccionada == 0)
         cout << endl << "Cliente NO valido" << endl;
         
      else {
          cout << endl << endl << "CUENTA SELECCIONADA"  << endl;
          cout <<         "===================" << endl << endl;
          cuentaSeleccionada->imprimir();  
          this->cajeroConsola.setCuenta(cuentaSeleccionada); 
          this->cajeroConsola.menu();
      }
}

void Banco::consultarSaldoCajero(){
     cout << endl << endl << "SALDO ACTUAL DEL CAJERO AUTOMATICO" << endl << endl;
     this->cajeroConsola.desgloseBilletes();
}

void Banco::pintarMenu(){
     
     cout << endl << endl << "MENU PRINCIPAL DEL BANCO" << endl << endl;
     cout << "Seleccione una opcion:" << endl;
     cout << "1. Listar cuentas" << endl;
     cout << "2. Operaciones con Cajero" << endl;  
     cout << "3. Consultar saldo y desglose del Cajero" << endl;  
     cout << "4. SALIR" << endl << endl;
     cout << "Opcion: ";
}

void Banco::menu(){
     int op;
     
     do {
         this->pintarMenu();
         cin >> op;
         
         switch(op){
           case LISTAR:
                this->listarCuentas();
                break;
                
           case CAJERO:
                this->operarConCajero();
                break;
                
           case SALDO_CAJERO:
                this->consultarSaldoCajero();
                break;
                     
           }
         
     } while (op != SALIR_BANCO); 
     this->grabarCuentas();    
}

void Banco::grabarCuentas(){
     BancoFile bf;
     
     if (bf.save(this->cuentas, this->fichero))
        cout << endl << endl << "FICHERO DE CUENTAS ACTUALIZADO" << endl << endl;
     else
        cout << endl << endl << "FICHERO DE CUENTAS NO SE PUDO ACTUALIZAR" << endl << endl;
     cin.get();
}

Banco::~Banco()
{
   for (int i = 0 ; i < this->cuentas.size() ; i++)
       delete this->cuentas.at(i);

}
