// Class automatically generated by Dev-C++ New Class wizard
#include <iostream>
#include "cajeroconsola.h" // class's header file
#include "cajerofile.h"

using namespace std;

CajeroConsola::CajeroConsola(string fichero)
{
    CajeroFile cf;
      
    this->fichero = fichero;
	this->cajero = cf.load(fichero);
	this->cuenta = 0;
}

void CajeroConsola::pedirSaldo(){
     cout << endl << endl << "SU SALDO ES: " << this->cuenta->getSaldo() << endl;     
}

void CajeroConsola::sacarDinero(){
     
     int importe;
     map<int,int> billetes_retirados;
     map<int,int>::reverse_iterator it;
     
     do {
         cout << endl << endl;
         cout << "Introduzca importe a retirar:";
         cin >> importe;
         
         if (importe <= 0 || importe % 10 != 0)
            cout << endl << "El importe NO es correcto" << endl;
         
     } while (importe <= 0 || importe % 10 != 0);
     
     if (importe > cuenta->getSaldo())
        cout << endl << "NO tiene saldo suficiente ..." << endl << endl;
     
     else {
          if (this->cajero.retirar(importe, billetes_retirados)){
             cout << endl << "Billetes retirados" << endl;
       
             for (it = billetes_retirados.rbegin(); it != billetes_retirados.rend() ; it++)
                 cout << "De " << it->first << ": " << it->second <<  endl; 
                 
             // Actualizar saldo de la cuenta:
             this->cuenta->actualizarSaldo(-importe);  
          }                                
    }  
}

void CajeroConsola::ingresarDinero(){
     int b100,b50,b20,b10;
     int importe;
     
     cout << endl << "Introduzca los billetes a ingresar" << endl;
     cout << "De 100: ";
     cin >> b100;
     
     cout << "De 50: ";
     cin >> b50;
     
     cout << "De 20: ";
     cin >> b20;
     
     cout << "De 10: ";
     cin >> b10;
     
     importe = this->cajero.ingresar(b100,b50,b20,b10);
     cout << endl << "Ha ingresado " << importe << endl << endl;
     
     // Actualizar saldo de la cuenta:
     this->cuenta->actualizarSaldo(importe);  
     
}

void CajeroConsola::desgloseBilletes(){
     this->cajero.imprimir();
}

void CajeroConsola::pintarMenu(){
     
     cout << endl << endl << "MENU PRINCIPAL - CAJERO AUTOMATICO" << endl << endl;
     cout << "Seleccione una opcion:" << endl;
     cout << "1. Consultar saldo" << endl;
     cout << "2. Ingresar dinero" << endl;
     cout << "3. Retirar dinero" << endl;
     cout << "4. SALIR" << endl << endl;
     cout << "Opcion: ";
}

void CajeroConsola::menu(){
     int op;
     
     do {
         this->pintarMenu();
         cin >> op;
         
         switch(op){
           case SALDO:
                this->pedirSaldo();
                break;
                
           case INGRESO:
                this->ingresarDinero();
                break;
                
           case REINTEGRO:  
                this->sacarDinero();
                break;                        
           }
         
     } while (op != SALIR); 
     this->grabarBilletes();
          
}

void CajeroConsola::grabarBilletes(){
     CajeroFile cf;
     
     cf.save(this->cajero.getBilletes(), this->fichero);
}

CajeroConsola::~CajeroConsola()
{
	
}
