// Class automatically generated by Dev-C++ New Class wizard

#ifndef CAJEROCONSOLA_H
#define CAJEROCONSOLA_H

#include "Cajero.h"
#include "CuentaBancaria.h"
#include "CuentaDeAhorro.h"

#include <string>
using namespace std;

#define SALDO 1
#define INGRESO 2
#define REINTEGRO 3
#define SALIR 4

class CajeroConsola
{
    private:
        Cajero cajero;
        CuentaBancaria *cuenta;
        string fichero;
        
        void pedirSaldo();
        void sacarDinero();
        void ingresarDinero();
        void pintarMenu();  
        void grabarBilletes();      
        
	public:
		CajeroConsola(){}
        CajeroConsola(string);
		void menu();
		inline int getSaldo(){ return this->cajero.saldo(); }
		inline void setCuenta(CuentaBancaria *cuenta){ this->cuenta = cuenta; }
		void desgloseBilletes();
		~CajeroConsola();
};

#endif // CAJEROCONSOLA_H
