// Class automatically generated by Dev-C++ New Class wizard

#ifndef CUENTABANCARIA_H
#define CUENTABANCARIA_H

#include <string>
#include <iostream>
#include <vector>
using namespace std;

#include "Cliente.h"

class CuentaBancaria
{
    
    protected:
            string numeroCuenta;
            int clave;
            int password;
            double saldo;
            Cliente titular;
            
	public:
		CuentaBancaria(string,int,int,double,Cliente);
		CuentaBancaria(vector<string>);
		virtual string toCSV();
		virtual inline string getTipo(){ return "B"; }
		virtual inline void actualizarSaldo(double importe){ this->saldo += importe; }
		inline double getSaldo(){ return this->saldo; }		
		virtual void imprimir();
		inline bool validar(int clave, int pass){return this->clave == clave && this->password==pass;}
		~CuentaBancaria();
};

#endif // CUENTABANCARIA_H
