// Class automatically generated by Dev-C++ New Class wizard

#ifndef CUENTADEAHORRO_H
#define CUENTADEAHORRO_H

#include <iostream>
#include <vector>
#include <string>

using namespace std;

#include "cuentabancaria.h" // inheriting class's header file

/*
 * No description
 */
class CuentaDeAhorro : public CuentaBancaria
{
    friend ostream & operator<<(ostream &, const CuentaDeAhorro &);
    
    private:
            double penalizacion;
            
	public:
		// class constructor
		CuentaDeAhorro(string,int,int,double,Cliente,double=2.5);
		CuentaDeAhorro(vector<string>);
		inline string getTipo(){ return "A"; }
		string toCSV();
		void actualizarSaldo(double);
        void imprimir();	
		~CuentaDeAhorro();
};

#endif // CUENTADEAHORRO_H
